name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # no extra env
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # полный clone для тегов
          submodules: recursive  # нужен checkout submodule reghelp_client

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install build  # pep517/518 builder

      - name: Build sdist & wheel
        run: |
          cd reghelp_client
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
          packages-dir: reghelp_client/dist
