name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: reghelp_client
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # нужен полный clone, чтобы setuptools_scm увидел теги

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install build deps
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          python -m pip install --upgrade pip
          pip install build  # pep517/518 builder

      - name: Build sdist & wheel
        working-directory: ${{ env.PROJECT_DIR }}
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
          packages-dir: ${{ env.PROJECT_DIR }}/dist
