name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # полный clone для тегов

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Debug directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Root directory contents:"
          ls -la
          echo "reghelp_client directory contents:"
          ls -la reghelp_client/
          echo "pyproject.toml exists in root?:"
          test -f pyproject.toml && echo "YES" || echo "NO"

      - name: Clean previous builds
        run: |
          # Удаляем старые артефакты предыдущих сборок
          rm -rf dist build *.egg-info

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build sdist & wheel
        run: |
          python -m build

      - name: Validate distribution with twine
        run: |
          twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
          packages-dir: dist/
