name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # no extra env
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # полный clone для тегов
# no submodules needed

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools_scm[toml] twine

      - name: Build sdist & wheel
        run: |
          mkdir -p dist
          python -m build ./reghelp_client -o dist

      - name: Validate distribution with twine
        run: twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
          packages-dir: dist
